# This is a basic workflow to help you get started with Actions

name: Mlops CI 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    


jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Chkout code 

      - uses: actions/setup-python@v5
        name: install python
        with:
          python-version: "3.11.5"

      - name: install dependencies 
        run: |
              # This is a basic workflow to help you get started with Actions

name: Mlops CI 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    


jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Chkout code 

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"

      - name: install dependencies 
        run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install -r requirements.txt